### PR TITLE
Change to FileWrapper

### PR DESCRIPTION
**Pull request by garyluu**
Change for the ToolContainerfile, ToolTests, ToolDescriptor being changed to FileWrapper in TRS.  'descriptor'/'tests'/'containerfile' => 'content'.

### CODE REVIEW

**Comment by jaeddy** [comment]
Thanks, @garyluu — good catch.

Is the `FileWrapper` change live in production Dockstore? When I check through the swagger UI, I'm still seeing the old style responses:

**descriptor:**
```
curl -X GET "https://dockstore.org:8443/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2Fdockstore-testing%2Fmd5sum-checker%2F_cwl_checker/versions/develop/CWL/descriptor" -H "accept: application/json"
```

```json
{
  "descriptor": "cwlVersion: v1.0\nclass: Workflow\n\nrequirements:\n  - class: SubworkflowFeatureRequirement\n\n#dct:creator:\n#  '@id': http://orcid.org/0000-0002-7681-6415\n#  foaf:name: Brian O'Connor\n#  foaf:mbox: mailto:briandoconnor@gmail.com\n\n#dct:contributor:\n#  foaf:name: Denis Yuen\n#  foaf:mbox: mailto:denis.yuen@oicr.on.ca\n\ninputs:\n  input_file: File\n  expected_md5: string\n\noutputs:\n  workflow_output_file:\n    type: File\n    outputSource: checker/results_file\n\nsteps:\n  md5sum:\n    run: md5sum/md5sum-workflow.cwl\n    in:\n      input_file: input_file\n    out: [output_file]\n  checker:\n    run: checker/md5sum-checker.cwl\n    in:\n      input_file: md5sum/output_file\n      expected_md5: expected_md5\n    out: [results_file]\n\ndoc: |\n  This demonstrates how to wrap a \"real\" tool with a checker workflow that runs both the tool and a tool that performs verification of results\n",
  "type": "CWL",
  "url": "https://raw.githubusercontent.com/dockstore-testing/md5sum-checker/develop/checker-workflow-wrapping-workflow.cwl"
}
```

**tests:**
```
curl -X GET "https://dockstore.org:8443/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2Fdockstore-testing%2Fmd5sum-checker%2F_cwl_checker/versions/develop/CWL/tests" -H "accept: application/json"
```

```json
[
  {
    "test": "{\n  \"input_file\": {\n        \"class\": \"File\",\n        \"path\": \"md5sum.input\"\n    },\n    \"expected_md5\": \"00579a00e3e7fa0674428ac7049423e2\"\n}\n",
    "url": "https://raw.githubusercontent.com/dockstore-testing/md5sum-checker/develop/checker-input-cwl.json"
  }
]
```

**Comment by garyluu** [comment]
The FileWrapper isn't live in Dockstore production yet.  It is on Dockstore staging though.

**Comment by jaeddy** [comment]
Ah, ok. So is "https://staging.dockstore.org:8443/api/ga4gh/v2/" the endpoint I should use for testing for now?

**Comment by garyluu** [comment]
Here's the swagger for staging: https://staging.dockstore.org/static/swagger-ui/index.html

The basePath endpoint ended up changing to https://staging.dockstore.org/api/api/ga4gh/v2

We'll be releasing to production sometime early September.

**Pull request merged**
